'use client';
import {useEffect,useRef,useState} from 'react';
import {MapPin,LocateFixed,Send,CheckCircle2,ArrowLeft} from 'lucide-react';
import {Button} from '@/components/ui/button';
import LocCore from '../../lib/location-core';
import {api,date,message,Point} from '../../lib/client';
// The tested sampler is shared with the original static pilot. No location is uploaded by it.
import type {CaptureRecord,Session} from '../../lib/location-types';
export default function Sender(){
 const [t,setT]=useState(''),[invite,setInvite]=useState<{label:string;submitted:boolean}|null>(null),[error,setError]=useState(''),[record,setRecord]=useState<CaptureRecord|null>(null),[running,setRunning]=useState(false),[sending,setSending]=useState(false),[sent,setSent]=useState(false),[tick,setTick]=useState(0),[wechat,setWechat]=useState(false);
 const session=useRef<Session|null>(null),start=useRef(0),payload=useRef<unknown>(null),sendLock=useRef(false);
 useEffect(()=>{const token=new URLSearchParams(location.hash.slice(1)).get('t')||'';setT(token);setWechat(/MicroMessenger/i.test(navigator.userAgent));if(!token){setError('这不是完整的邀请链接，请让对方在接收页面生成并发送链接。');return;}void api<{label:string;submitted:boolean}>('/api/invite','POST',{token}).then(r=>setInvite(r)).catch(e=>setError(message(e)));const stop=()=>session.current?.stop('interrupted');window.addEventListener('pagehide',stop);const vis=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',vis);return()=>{session.current?.stop('interrupted');window.removeEventListener('pagehide',stop);document.removeEventListener('visibilitychange',vis);};},[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setTick(Math.min(60,Math.floor((Date.now()-start.current)/1000))),500);return()=>clearInterval(id);},[running]);
 function locate(){session.current?.stop();setRecord(null);setSent(false);payload.current=null;setError('');setTick(0);start.current=Date.now();setRunning(true);const id=crypto.randomUUID();session.current=LocCore.createSession({id,testId:id,scene:'自动回传',device:'',geolocation:navigator.geolocation,onUpdate:(r:CaptureRecord)=>setRecord(r),onFinish:(r:CaptureRecord)=>{setRecord(r);setRunning(false);}});session.current.start();}
 async function send(){if(sendLock.current||!record?.position||record.status!=='success')return;sendLock.current=true;setSending(true);setError('');payload.current??={token:t,submissionId:crypto.randomUUID(),confirmed:true,position:record.position};try{await api('/api/submit','POST',payload.current);setSent(true);}catch(e){setError(message(e)+' 只有出现“发送成功”才表示本页已确认。可以再次点击，重试不会重复生成记录。');}finally{setSending(false);sendLock.current=false;}}
 const p=record?.position as Point|undefined;
 return <main className="shell sender-shell"><header className="top"><span className="brand"><span className="brand-icon"><MapPin size={22}/></span>定位接力<small>长期入口 · 主动发送</small></span></header><section className="send-panel panel"><div className="eyebrow">朋友发来的位置邀请</div><h1>{sent?'位置已发送':'把你的位置发给对方'}</h1><p className="muted">{invite?`邀请备注：${invite.label}`:'正在检查邀请…'}</p>{error&&<p className="alert" role="alert">{error}</p>}{wechat&&!sent&&<p className="notice">微信可能限制定位。若无法定位，请点右上角“…” → 在浏览器打开。</p>}{sent?<div className="success-state"><CheckCircle2 size={48}/><h2>发送成功</h2><p>对方的接收页面会自动出现你的记录。<br/>这个链接以后也能继续使用。</p><Button className="action wide" onClick={locate}>再次获取我的位置</Button></div>:invite&&<><ol className="send-steps"><li className={!p?'active':''}>1 允许定位</li><li className={p?'active':''}>2 确认发送</li></ol><div className="location-state"><LocateFixed size={32}/><h2>{running?`正在定位 · ${tick} 秒`:p?'已取得本次位置':'先获取你当前的位置'}</h2><p>{running?'最多等待 60 秒，取得位置后继续观察 30 秒。':record?record.reason:'浏览器将询问定位权限，请选择允许。'}</p></div>{p&&<div className="position-preview"><div className="coordinates"><div><span>纬度</span><b>{p.lat.toFixed(6)}</b></div><div><span>经度</span><b>{p.lon.toFixed(6)}</b></div></div><p>设备报告精度：约 {Math.round(p.accuracy)} 米</p><small>{date(p.timestamp)} · {p.crs}</small></div>}{running?<Button className="action secondary wide" onClick={()=>session.current?.stop()}>{p?'结束观察，使用本次位置':'停止定位'}</Button>:<Button className={'action wide '+(p?'secondary':'')} onClick={locate} disabled={sending}><LocateFixed size={18}/>{record?'重新定位':'获取我的位置'}</Button>}<div className="consent"><p>点击下方按钮，将把本次经纬度、设备报告精度和采集时间上传给邀请你的人，保留最多 7 天。不会持续记录移动轨迹。</p><Button className="action wide" disabled={running||sending||record?.status!=='success'||!p} onClick={()=>void send()}><Send size={18}/>{sending?'正在发送…':'确认发送位置'}</Button></div></>}<p className="fine">精度为手机报告值，不等于实际误差。现场地址和入口请再人工核对。</p></section><footer>仅用于同事模拟测试 · 高德导航由接收者在自己的页面打开</footer></main>;
}
