import test from 'node:test';
import assert from 'node:assert/strict';
import './register-ts.mjs';
const {createAutoSession}=await import('../lib/auto-location.ts');
function fixture(){let now=Date.UTC(2026,8,26,12),success,error,finished=[],updates=[],cleared=0;const timers=new Map();const s=createAutoSession({geo:{watchPosition(a,b,options){success=a;error=b;assert.equal(options.maximumAge,0);return 1;},clearWatch(){cleared++;}},now:()=>now,schedule:(fn,ms)=>{timers.set(1,fn);return 1;},cancelTimer:id=>timers.delete(id),onUpdate:(p,r)=>updates.push([p,r]),onFinish:r=>finished.push(r)});return {finished,updates,stop:s.stop,cleared:()=>cleared,tick:n=>now+=n,timeout:()=>{now+=60000;timers.get(1)?.();},sample:(accuracy=20,patch={})=>success({timestamp:now,coords:{latitude:22.6,longitude:110.1,accuracy},...patch}),deny:()=>error({code:1}),unavailable:()=>error({code:2})};}
test('首次有效位置立即返回，几十米、几百米和几公里均不拦截',()=>{for(const accuracy of [0,20,60,80,300,3000,50000]){const f=fixture();f.sample(accuracy);assert.equal(f.finished.length,1);assert.equal(f.finished[0].status,'ready');assert.equal(f.finished[0].point.accuracy,accuracy);assert.equal(f.finished[0].elapsedMs,0);assert.equal(f.cleared(),1);}});
test('取得一次位置后停止采集，后续回调和计时器不会重复完成',()=>{const f=fixture();f.sample(80);f.tick(2000);f.sample(15,{coords:{latitude:23,longitude:111,accuracy:15}});f.timeout();f.deny();assert.equal(f.finished.length,1);assert.equal(f.finished[0].point.lat,22.6);assert.equal(f.finished[0].point.accuracy,80);assert.equal(f.cleared(),1);});
test('旧时间戳、未来时间和无效坐标仍被拒绝，之后的新结果可发送',()=>{const f=fixture();f.sample(15,{timestamp:Date.UTC(2020,0,1)});f.sample(15,{timestamp:Date.UTC(2026,8,26,13)});f.sample(15,{coords:{latitude:NaN,longitude:110,accuracy:15}});f.sample(-1);assert.equal(f.finished.length,0);f.sample(80);assert.equal(f.finished[0].status,'ready');assert.equal(f.finished[0].point.accuracy,80);});
test('主动停止后晚到的有效位置不能自动发送',()=>{const f=fixture();f.stop();f.tick(2000);f.sample(80);assert.equal(f.finished.length,1);assert.equal(f.finished[0].status,'cancelled');assert.equal(f.finished[0].point,null);});
test('第二次定位拒绝不能沿用第一次的位置',()=>{const first=fixture();first.sample(80);const second=fixture();second.deny();first.sample(15);second.sample(30);assert.equal(first.finished.length,1);assert.equal(second.finished.length,1);assert.equal(second.finished[0].status,'denied');assert.equal(second.finished[0].point,null);});
test('只有一直没有有效位置才等待到60秒，之后的回调不补发',()=>{const f=fixture();f.sample(80,{timestamp:Date.UTC(2020,0,1)});f.timeout();f.sample(80);assert.equal(f.finished.length,1);assert.equal(f.finished[0].status,'timeout');assert.equal(f.finished[0].point,null);assert.doesNotMatch(f.finished[0].reason,/未达到|标准/);});
test('暂时不可用不会妨碍随后的一次有效结果',()=>{const f=fixture();f.unavailable();f.tick(59000);f.sample(200);assert.equal(f.finished[0].status,'ready');assert.equal(f.finished[0].point.accuracy,200);});
test('同步回调也会清理定位监听和超时计时器',()=>{let cleared=0,finished=0,cancelled=0;createAutoSession({now:()=>1000,geo:{watchPosition(ok){ok({timestamp:1000,coords:{latitude:22,longitude:110,accuracy:80}});return 7;},clearWatch(id){assert.equal(id,7);cleared++;}},schedule:()=>0,cancelTimer:()=>cancelled++,onUpdate(){},onFinish:r=>{assert.equal(r.status,'ready');finished++;}});assert.equal(cleared,1);assert.equal(finished,1);assert.equal(cancelled,1);});
