import test from 'node:test';
import assert from 'node:assert/strict';
import './register-ts.mjs';
const {createPublicDelivery}=await import('../lib/public-delivery.ts');
const flush=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
function setup(t,fetch){t.mock.timers.enable({apis:['Date','setTimeout'],now:Date.UTC(2026,8,27)});t.mock.method(globalThis,'fetch',fetch);let success,error;const views=[];const d=createPublicDelivery({geo:{watchPosition(a,b){success=a;error=b;return 1;},clearWatch(){}},label:()=> '单元模拟',onChange:s=>views.push(s)});return {d,views,sample:accuracy=>success({timestamp:Date.now(),coords:{latitude:22,longitude:110,accuracy}}),deny:()=>error({code:1}),last:()=>views.at(-1)};}
const receipt=(revision=0)=>Response.json({received:true,receivedAt:Date.now(),revision,updatedAt:revision?Date.now():null});
test('先显示首次成功，采集结束后只PATCH同一编号一次',async t=>{const requests=[];const f=setup(t,async(path,init)=>{requests.push({path,...init});return receipt(init.method==='PATCH'?1:0);});f.sample(80);await flush();assert.equal(f.last().delivered.accuracy,80);assert.equal(f.last().refining,true);t.mock.timers.tick(5000);f.sample(20);assert.equal(requests.length,1);t.mock.timers.tick(15000);await flush();assert.equal(requests.length,2);assert.equal(requests[1].method,'PATCH');assert.ok(requests[1].path.endsWith(JSON.parse(requests[0].body).id));assert.equal(f.last().delivered.accuracy,20);assert.equal(f.last().refining,false);f.sample(1);await flush();assert.equal(requests.length,2);f.d.stop();});
test('断网重试载荷不变，服务确认前不提前发精度更新',async t=>{const requests=[];let resolveFirst;const f=setup(t,(path,init)=>{requests.push({path,...init});if(requests.length===1)return Promise.reject(Error('offline'));if(init.method==='POST')return new Promise(resolve=>resolveFirst=resolve);return Promise.resolve(receipt(1));});f.sample(80);await flush();t.mock.timers.tick(1000);f.sample(20);t.mock.timers.tick(1000);await flush();assert.equal(requests.length,2);assert.equal(requests[0].body,requests[1].body);t.mock.timers.tick(18000);await flush();assert.equal(requests.length,2);resolveFirst(receipt());await flush();assert.equal(requests[2].method,'PATCH');assert.equal(f.last().delivered.accuracy,20);f.d.stop();});
test('已送达后切后台停止，后来的更好结果不再发',async t=>{const requests=[];const f=setup(t,async(path,init)=>{requests.push(init);return receipt();});f.sample(80);await flush();f.d.stop();t.mock.timers.tick(5000);f.sample(10);t.mock.timers.tick(60000);await flush();assert.equal(requests.length,1);assert.equal(f.last().delivered.accuracy,80);assert.equal(f.last().refining,false);});
test('停止发生在弱网退避中，不再重试，也不报告成功',async t=>{let n=0;const f=setup(t,async()=>{n++;throw Error('offline');});f.sample(80);await flush();f.d.stop();t.mock.timers.tick(120000);await flush();assert.equal(n,1);assert.equal(f.last().delivered,null);assert.equal(f.last().phase,'stopped');});
test('服务器拒绝首次数据后不沿用成功状态、不自动重试',async t=>{let n=0;const f=setup(t,async()=>{n++;return Response.json({error:'位置已过期',code:'POSITION_EXPIRED'},{status:400});});f.sample(80);await flush();assert.equal(f.last().delivered,null);assert.equal(f.last().phase,'failed');assert.equal(f.last().canRetry,false);t.mock.timers.tick(20000);await flush();assert.equal(n,1);f.d.stop();});
