import test from 'node:test';
import assert from 'node:assert/strict';
import './register-ts.mjs';
const {createAutoSession}=await import('../lib/auto-location.ts');
const {retryRequest}=await import('../lib/delivery-retry.ts');
const {RequestError}=await import('../lib/request-error.ts');
const {createMapQueryQueue}=await import('../lib/map-query-queue.ts');
const {wantedRecords,mapKey}=await import('../lib/public-board-model.ts');
const {describePlace}=await import('../lib/place-description.ts');
function capture(){let now=100000,success,error,n=0,cleared=0;const timers=new Map(),first=[],finished=[];
 const session=createAutoSession({geo:{watchPosition(a,b){success=a;error=b;return 7;},clearWatch(){cleared++;}},now:()=>now,schedule:(fn,ms)=>{timers.set(++n,{fn,at:now+ms});return n;},cancelTimer:id=>timers.delete(id),onFirst:p=>first.push(p),onUpdate(){},onFinish:r=>finished.push(r)});
 return {first,finished,session,cleared:()=>cleared,sample:(accuracy,patch={})=>success({timestamp:now,coords:{latitude:22,longitude:110,accuracy},...patch}),deny:()=>error({code:1}),tick(ms){const end=now+ms;while(true){const next=[...timers].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;now=next[1].at;timers.delete(next[0]);next[1].fn();}now=end;}};
}
test('首次80米立即交付，20秒内择优，之后只完成一次',()=>{const c=capture();c.sample(80);assert.equal(c.first.length,1);assert.equal(c.finished.length,0);c.tick(5000);c.sample(20);c.tick(5000);c.sample(40);c.tick(10000);assert.equal(c.finished[0].point.accuracy,20);c.sample(1);c.tick(60000);assert.equal(c.finished.length,1);assert.equal(c.cleared(),1);});
test('改善需同时达到20%及10米，未达标保留首次点',()=>{for(const [a,b,expected] of [[80,65,80],[20,15,20],[50,40,40],[100,80,80]]){const c=capture();c.sample(a);c.tick(500);c.sample(b);c.tick(20000);assert.equal(c.finished[0].point.accuracy,expected);}});
test('晚取得首次点仍遵守采集总上限60秒',()=>{const c=capture();c.tick(55000);c.sample(300);c.tick(1000);c.sample(50);c.tick(4000);assert.equal(c.finished[0].elapsedMs,60000);assert.equal(c.finished[0].point.accuracy,50);});
test('停止、拒绝和过时回调均不能产生精度更新',()=>{for(const stop of ['session','deny']){const c=capture();c.sample(80);c.tick(1000);if(stop==='session')c.session.stop();else c.deny();c.sample(10);c.tick(60000);assert.equal(c.finished.length,1);assert.equal(c.finished[0].point,null);}});
test('无新位置时60秒结束，旧位置不能成为首次点',()=>{const c=capture();c.sample(15,{timestamp:99999});c.tick(60000);assert.equal(c.first.length,0);assert.equal(c.finished[0].status,'timeout');});
function retryFixture(){let now=0;const waits=[],timeouts=[],controller=new AbortController();return {waits,timeouts,controller,run:fn=>retryRequest(ms=>{timeouts.push(ms);return fn();},{signal:controller.signal,deadline:120000,now:()=>now,wait:async ms=>{waits.push(ms);now+=ms;}})};}
test('弱网最多三次自动重试，退避为2、5、10秒，每次最多15秒',async()=>{const f=retryFixture();let attempts=0;assert.equal(await f.run(async()=>{if(++attempts<4)throw new RequestError('offline');return 'ok';}),'ok');assert.deepEqual(f.waits,[2000,5000,10000]);assert.deepEqual(f.timeouts,[15000,15000,15000,15000]);});
test('持续故障达到重试次数上限即停止',async()=>{const f=retryFixture();let attempts=0;await assert.rejects(f.run(async()=>{attempts++;throw new RequestError('busy',503);}));assert.equal(attempts,4);});
test('参数、冲突、无权限与容量错误不自动重试',async()=>{for(const e of [new RequestError('bad',400),new RequestError('conflict',409),new RequestError('forbidden',403),new RequestError('full',429,'RECORDS_FULL')]){const f=retryFixture();await assert.rejects(f.run(async()=>{throw e;}));assert.equal(f.waits.length,0);}});
test('Retry-After得到尊重，但不能突破2分钟边界',async()=>{const f=retryFixture();let tries=0;await f.run(async()=>{if(!tries++)throw new RequestError('busy',429,'',8000);return 1;});assert.deepEqual(f.waits,[8000]);const g=retryFixture();await assert.rejects(g.run(async()=>{throw new RequestError('busy',429,'',120000);}),e=>e.code==='AUTO_RETRY_ENDED');assert.equal(g.waits.length,0);});
test('停止重试后不再发请求，剩余时间限制单次请求',async()=>{const f=retryFixture();f.controller.abort();let n=0;await assert.rejects(f.run(async()=>++n),e=>e.name==='AbortError');assert.equal(n,0);await retryRequest(async ms=>assert.equal(ms,5000),{signal:new AbortController().signal,deadline:5000,now:()=>0});});
const flush=()=>new Promise(resolve=>setImmediate(resolve));
test('地图查询并发不超过2，刷新不重复，失败只在显式重试后重发',async()=>{const pending=new Map(),calls=[],errors=[];const q=createMapQueryQueue({key:x=>x,query:x=>{calls.push(x);return new Promise((resolve,reject)=>pending.set(x,{resolve,reject}));},onResult(){},onError:k=>errors.push(k)});q.setTasks(['selected','new','old']);await flush();assert.deepEqual(calls,['selected','new']);pending.get('selected').resolve(1);await flush();assert.deepEqual(calls,['selected','new','old']);pending.get('new').reject(Error('quota'));pending.get('old').resolve(1);await flush();q.setTasks(['selected','new','old']);await flush();assert.equal(calls.length,3);assert.deepEqual(errors,['new']);q.retry('new');await flush();assert.equal(calls.length,4);q.stop();pending.get('new').resolve(1);});
test('优先所选和最新10条，再查询可见历史，新修订使用新键',()=>{const rows=Array.from({length:30},(_,i)=>({id:String(i),revision:0,lat:22,lon:110,accuracy:80,crs:'WGS84'}));const wanted=wantedRecords(rows,'25',['26','0']);assert.equal(wanted[0].id,'25');assert.equal(wanted.length,12);assert.ok(wanted.some(r=>r.id==='26'));assert.notEqual(mapKey(rows[0]),mapKey({...rows[0],revision:1}));});
test('大于200米时只说明片区，不输出具体建筑方位或门牌',()=>{const raw={formattedAddress:'某建筑1号',addressComponent:{province:'广西',city:'玉林市',district:'玉州区',streetNumber:{street:'示例街'}},pois:[{name:'试验大厦',location:'110,22'}]};const rough=describePlace(raw,[110.001,22],201);assert.equal(rough.title,'广西玉林市玉州区示例街');assert.equal(rough.relative,'');assert.doesNotMatch(rough.title+rough.address,/试验大厦|1号/);assert.match(describePlace(raw,[110.001,22],200).title,/试验大厦/);});
