// The SDK owns map rendering, coordinate conversion and route planning.
// Narrow the unknown provider result before using it in user-visible text.
/* eslint-disable @typescript-eslint/no-explicit-any */
import type {Point} from './client';
export type AMapSDK=any;
let loading:Promise<AMapSDK>|null=null;
export function loadAMap(){if((window as any).AMap)return Promise.resolve((window as any).AMap);if(loading)return loading;loading=(async()=>{const r=await fetch('/api/map-config',{cache:'no-store'});const cfg=await r.json() as {configured:boolean;key:string;error?:string};if(!r.ok)throw Error(cfg.error||'地图服务暂不可用，位置接收仍可使用');if(!cfg.configured)throw Error('地图尚未配置高德 Key，暂时无法显示地图和地点名称');const w=window as any;if(w.AMap)return w.AMap;w._AMapSecurityConfig={serviceHost:location.origin+'/_AMapService'};return await new Promise<AMapSDK>((resolve,reject)=>{const s=document.createElement('script');const timer=setTimeout(()=>{s.remove();reject(Error('高德地图加载超时，请检查网络后重试'));},15000);s.referrerPolicy='strict-origin-when-cross-origin';s.src='https://webapi.amap.com/maps?v=2.0&key='+encodeURIComponent(cfg.key)+'&plugin=AMap.Geocoder,AMap.Driving,AMap.Scale,AMap.ToolBar';s.onload=()=>{clearTimeout(timer);w.AMap?resolve(w.AMap):reject(Error('高德地图未加载成功'));};s.onerror=()=>{clearTimeout(timer);s.remove();reject(Error('无法连接高德地图，请检查网络'));};document.head.appendChild(s);});})();loading.catch(()=>{loading=null;});return loading;}
export function converted(A:AMapSDK,p:Pick<Point,'lat'|'lon'|'crs'>):Promise<[number,number]>{if(p.crs==='GCJ02')return Promise.resolve([p.lon,p.lat]);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('坐标转换超时')),12000);A.convertFrom([p.lon,p.lat],'gps',(status:string,result:any)=>{clearTimeout(timer);const a=result?.locations?.[0];if(status!=='complete'||!a)return reject(Error('坐标转换未成功，未绘制可能偏移的点'));const lon=typeof a.getLng==='function'?a.getLng():a.lng,lat=typeof a.getLat==='function'?a.getLat():a.lat;if(!Number.isFinite(lon)||!Number.isFinite(lat))return reject(Error('转换结果无效'));resolve([lon,lat]);});});}
export function addressFor(A:AMapSDK,coordinates:[number,number]):Promise<unknown>{return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('地点查询超时')),12000);new A.Geocoder({extensions:'all',radius:200}).getAddress(coordinates,(status:string,result:any)=>{clearTimeout(timer);if(status==='complete'&&result?.regeocode)resolve(result.regeocode);else{const info=typeof result==='string'?result:String(result?.info||'');reject(Error(/LIMIT|QUOTA|TOO_FREQUENT/.test(info)?'高德查询已达服务上限，请稍后再试':/KEY|SIGNATURE|SCODE|PERMISSION|AUTH/.test(info)?'高德地图授权失败，请管理者检查配置':status==='no_data'?'此处暂无高德地点名称，可切换海外地图核对':'高德地点查询失败，请重试或切换地图'));}});});}
